-- ============================================================
-- Booking Site Schema Migration
-- Brand: Villa Verde Miami
-- Confirmation prefix: VV
-- Generated by booking-site-service
-- ============================================================

-- Enable required extensions (pg_net for HTTP calls from functions)
CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;


-- ============================================================
-- 1. BOOKINGS
-- ============================================================

CREATE TABLE IF NOT EXISTS bookings (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  confirmation_code       text NOT NULL UNIQUE,
  property_slug           text NOT NULL,
  property_name           text NOT NULL,
  check_in                date NOT NULL,
  check_out               date NOT NULL,
  guests                  integer NOT NULL DEFAULT 1,
  nights                  integer NOT NULL,
  guest_first_name        text NOT NULL,
  guest_last_name         text NOT NULL,
  guest_email             text NOT NULL,
  guest_phone             text NOT NULL,
  special_requests        text,
  nightly_rate            integer NOT NULL,
  subtotal                integer NOT NULL,
  cleaning_fee            integer NOT NULL,
  service_fee             integer NOT NULL,
  taxes                   integer NOT NULL,
  total                   integer NOT NULL,
  stripe_payment_intent_id text,
  status                  text NOT NULL DEFAULT 'pending'
                          CHECK (status IN ('pending', 'confirmed', 'cancelled')),
  created_at              timestamptz DEFAULT now(),
  updated_at              timestamptz DEFAULT now()
);

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "Service role full access on bookings"
  ON bookings
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Authenticated users can read their own bookings by email
CREATE POLICY "Users can read own bookings"
  ON bookings
  FOR SELECT
  TO authenticated
  USING (guest_email = auth.jwt()->>'email');

-- Index: confirmation_code uniqueness is enforced by the UNIQUE constraint
-- (which creates bookings_confirmation_code_key automatically)


-- ============================================================
-- 2. CALENDAR AVAILABILITY
-- ============================================================

CREATE TABLE IF NOT EXISTS calendar_availability (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  property_slug   text NOT NULL,
  date            date NOT NULL,
  is_blocked      boolean NOT NULL DEFAULT false,
  source          text DEFAULT 'airbnb',
  summary         text,
  updated_at      timestamptz DEFAULT now(),
  UNIQUE (property_slug, date)
);

ALTER TABLE calendar_availability ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "Service role full access on calendar_availability"
  ON calendar_availability
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Anyone can read availability (public calendar)
CREATE POLICY "Public read access"
  ON calendar_availability
  FOR SELECT
  TO public
  USING (true);

-- Performance index for date range queries per property
CREATE INDEX IF NOT EXISTS idx_calendar_availability_slug_date
  ON calendar_availability (property_slug, date);


-- ============================================================
-- 3. GUEST EMAILS LOG
-- ============================================================

CREATE TABLE IF NOT EXISTS guest_emails_log (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id  uuid REFERENCES bookings (id),
  template    text NOT NULL,
  sent_to     text NOT NULL,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE guest_emails_log ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "Service role full access on guest_emails_log"
  ON guest_emails_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Indexes for querying by booking and by template
CREATE INDEX IF NOT EXISTS idx_guest_emails_log_booking
  ON guest_emails_log (booking_id);

CREATE INDEX IF NOT EXISTS idx_guest_emails_log_template
  ON guest_emails_log (template);


-- ============================================================
-- 4. NEWSLETTER SUBSCRIBERS
-- ============================================================

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email           text NOT NULL UNIQUE,
  subscribed_at   timestamptz DEFAULT now(),
  unsubscribed_at timestamptz
);

ALTER TABLE newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "Service role full access on newsletter_subscribers"
  ON newsletter_subscribers
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Anonymous users can subscribe (insert)
CREATE POLICY "Anon insert"
  ON newsletter_subscribers
  FOR INSERT
  TO public
  WITH CHECK (true);

-- Anonymous users can update (e.g. unsubscribe)
CREATE POLICY "Anon update"
  ON newsletter_subscribers
  FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);


-- ============================================================
-- 5. CONTACT SUBMISSIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS contact_submissions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text NOT NULL,
  email       text NOT NULL,
  subject     text,
  message     text NOT NULL,
  created_at  timestamptz DEFAULT now()
);

ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;

-- Service role can do everything
CREATE POLICY "Service role full access on contact_submissions"
  ON contact_submissions
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Anonymous users can submit the contact form
CREATE POLICY "Anon insert"
  ON contact_submissions
  FOR INSERT
  TO public
  WITH CHECK (true);


-- ============================================================
-- FUNCTION: invoke_scheduled_emails
--
-- Called by Supabase pg_cron to trigger the process-scheduled-emails
-- edge function. Reads project_url and anon_key from Supabase Vault.
--
-- Usage (cron example):
--   SELECT cron.schedule(
--     'process-scheduled-emails',
--     '*/15 * * * *',
--     $$SELECT invoke_scheduled_emails('["check-in-reminder","check-out-reminder"]'::jsonb)$$
--   );
-- ============================================================

CREATE OR REPLACE FUNCTION invoke_scheduled_emails(templates jsonb)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  project_url text;
  anon_key text;
BEGIN
  SELECT decrypted_secret INTO project_url
    FROM vault.decrypted_secrets WHERE name = 'project_url';

  SELECT decrypted_secret INTO anon_key
    FROM vault.decrypted_secrets WHERE name = 'anon_key';

  PERFORM net.http_post(
    url := project_url || '/functions/v1/process-scheduled-emails',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || anon_key,
      'apikey', anon_key
    ),
    body := jsonb_build_object('templates', templates)
  );
END;
$$;
